version: '2'
services:
  portal:
    build: liferay
    volumes:
     - ./portal-ext.properties:/usr/local/liferay-ce-portal-7.0-ga4/portal-ext.properties
    ports:
     - "8080:8080"
    depends_on:
     - mariadb
     - elasticsearch
  mariadb:
    build: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=liferay
      - MYSQL_DATABASE=lportal
      - character-set-server=utf8mb4
      - collation-server=utf8mb4_unicode_ci
  elasticsearch:
      build: elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"